os: linux
sudo: required
language: "minimal"
services:
  - docker

before_script:
  - docker pull toliak/bootstrap-cpp

jobs:
  include:
    - name: "tests"
      script:
        - docker run -t -v $(pwd):/var/builder -w /var/builder --entrypoint ./scripts/tests.sh toliak/bootstrap-cpp
    - name: "coverage"
      script:
        - docker run -t -v $(pwd):/var/builder -w /var/builder --entrypoint ./scripts/coverage.sh toliak/bootstrap-cpp
  - name: "quality"
      script:
        - ./scripts/genenv.sh
        - docker run --env-file .env -v pwd:pwd -w pwd -t rusdevops/bootstrap-cpp scripts/coverage.sh
      # The bot has gone...
      # - docker run --env-file .env -v pwd:pwd -w pwd -t rusdevops/bootstrap-cpp scripts/duplication.sh

notifications:
  email: false
